services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      # Notebooki i pliki projektu - zmiany zapisują się na dysku hosta
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
