name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pillow=9.4.0
  - pandas=1.4.1
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - plotly=5.1.0
  - pydot=1.4.2
  - jupyterlab=4.2.5
  - matplotlib=3.4.3
  - ipywidgets=8.1.2
  - pip
  - pip:
      - tensorflow==2.15
      - graphviz==0.20.3
