name: ml_test
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - tensorflow=2.5
  - pandas=1.4.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - plotly=5.1.0
  - sweetviz=2.1.3
  - opencv=4.5.2
  - keras=2.4.3
  - pydot=1.2.4
  - graphviz=2.40.1
  - pyaescrypt=6.0.0
